name: alamoadac_website
description: "ala moodac"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.0.0
  cached_network_image: ^3.2.0 
  shared_preferences: ^2.0.15
  path: ^1.8.0
  google_fonts: ^6.2.0
  lottie: ^1.4.2
  skeletonizer: ^1.4.2
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  image_picker: ^0.8.7+5
  translator: ^1.0.3+1
  animate_do: ^3.0.2
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.1.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.5
  dropdown_button2: ^2.0.0
  material_design_icons_flutter: ^5.0.6595
  flutter_svg: ^2.0.5 
  app_links: ^6.4.0
  share_plus: ^10.1.4
  permission_handler: ^11.0.0
  get: ^4.6.7
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  animated_widgets: ^1.1.0
  showcaseview: ^3.0.0
  photo_view: ^0.15.0
  flutter_spinkit: ^5.1.0
  flutter_cache_manager: ^3.3.0






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  color: "#ffffff"  # اللون الخلفي لشاشة الـ Splash
  image: "assets/images/logo_open.png"  # مسار الصورة التي تريد عرضها في الـ Splash
  android: true
  ios: true
  web: true
  fullscreen: true  # اجعل الشاشة بالكامل بدون عناصر واجهة المستخدم الأخرى

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/play_store_512.png"
  adaptive_icon_background: "#EB9E2B"
  adaptive_icon_foreground: "assets/images/play_store_512.png"
  min_sdk_android: 21

flutter:

 
  uses-material-design: true
  assets:
   - assets/
   - assets/fonts/
   - assets/images/
   - assets/logos/



  fonts:
  - family:          DinarOne
    fonts:
     - asset:        assets/fonts/GE Dinar One Medium.ttf

   
fonts:
- family: MaterialIcons
  fonts:
    - asset: assets/fonts/MaterialIcons-Regular.otf
